import { defineConfig } from 'orval';

/**
 * Typed client of the backend API, generated from its OpenAPI schema (`make api` at the repository root): one
 * `fetch` function per route and the response types, in `src/api/generated/`. The app calls these functions from its
 * `*QueryOptions` factories (TanStack Query), never `fetch` on the API.
 */
export default defineConfig({
  smartMeetingApi: {
    input: './openapi/smart-meeting.openapi.json',
    output: {
      mode: 'split',
      target: './src/api/generated/smartMeetingApi.ts',
      schemas: './src/api/generated/model',
      client: 'fetch',
      clean: true,
      override: {
        header: (info) => [
          'Generated by orval from the backend OpenAPI schema. Do not edit manually.',
          `${info.title} ${info.version}`,
        ],
        mutator: {
          path: './src/api/smartMeetingClient.ts',
          name: 'smartMeetingClient',
          default: true,
        },
        fetch: {
          includeHttpResponseReturnType: false,
        },
      },
    },
  },
});
